version: '3.9'
services:
  fpl_vuejs_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fpl/vuejs-app
    container_name: fpl_vuejs_app
    working_dir: /app
    volumes:
      - .:/app
    restart: unless-stopped
    ports:
      - '8080:80'
    networks:
      - app-network
    depends_on:
      - fpl_api

  fpl_api:
    image: vladerc/git-php-nginx:v1.1
    environment:
      GIT_REPO: 'https://github.com/VladErc/favourite-programming-language-api.git'
      INDEX_FILE: 'index.php'
      DOCUMENT_ROOT: '/public'
    container_name: fpl_api
    restart: unless-stopped
    ports:
      - '8081:80'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
